Repository lenianiva/lean4-nix, pull requests merged in 2024-12, with the labels that each got.

#30 chore: Add formatter (`alejandra`)
  README.md
  checks.nix
  flake.nix
  lake.nix
  lib/packages.nix
  manifests/v4.11.0.nix
  manifests/v4.12.0.nix
  manifests/v4.13.0.nix
  overlay.nix
  templates/dependency/flake.nix
  templates/minimal/flake.nix
Labels: refactor

#31 refactor: clean up and remove old hacks
  README.md
  flake.nix
  lib/packages.nix
  templates/dependency/flake.nix
  templates/minimal/flake.nix
Labels: part/overlay, refactor

#29 feat: Manifest for v4.14.0
  lake.nix
  manifests/default.nix
  manifests/v4.14.0.nix
  templates/dependency/lake-manifest.json
  templates/dependency/lakefile.lean
  templates/dependency/lean-toolchain
  templates/minimal/lean-toolchain
Labels: feature, part/manifest
